package blockproject.bpsl.ast.expr;

public enum EType
{
    BINARY_OPERATION,
    UNARY_OPERATION,
    FUNCTION_CALL,
    ARRAY_SUBSCRIPT,
    MEMBER_ACCESS,
    MEMBER_FUNCTION_CALL,
    PRIMARY,
    FLOAT_LITTERAL,
    DOUBLE_LITTERAL,
    IDENTIFIER,
    STRING_LITTERAL,
}